import "./globals.css";
import { Roboto } from "next/font/google";
import Navbar from "@/components/Navbar";

/*Los metadatos se pueden poner en cada componente siempre y cuando se renderizen en el servidor */
export const metadata = {
  title: "Probando Next JS 13",
  description: "Generated by create next app",
  icons: {
    icons: [
      "https://res.cloudinary.com/dthpuldpm/image/upload/v1679173117/aTempo/favicon_at4qsk.png",
    ],
  },
};

/*Para poder usar las fuentes de Google primero debemos guardar las propiedades en una variable
Luego se deben usar en el main para que toda la pagina se vea afectada por esa fuente*/
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

/*Este es el HTML principal, dicha etiqueta no se puede volver a repetir en ningun lado*/
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-slate-300`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
